config/routes.rb
Dengue::Application.routes.draw do
  
  resources :feedbacks

  resources :notices

  match "/home/:id" => "home#index", :as => "Home"
  match "/faq" => 'home#faq'
  match "/manual" => "home#manual"
  match "/howto" => "home#howto"
  match '/contact' => 'home#contact'
  match 'about' => 'home#about'
  match '/education' => 'home#education'
  match '/credit' => 'home#credit'

  match "/user/:id/prize_codes" => 'prize_codes#index'
  match "/user/:id/prize_codes/:prize_id" => 'prize_codes#show'
  match "/user/:id/prize_codes/:prize_id/redeem/:prize_code_id" => 'prize_codes#redeem'
  post 'premios/:id' => "prizes#new_prize_code"
  match "/user/:id/buy_prize/:prize_id" => 'users#buy_prize'
  get "dashboard/index"
  get "password_resets/new"
  post "reports/sms"
  
  get "torpedos/:id" => "reports#torpedos"
  get "/sb/rest/sms/inject" => "sms_gateway#inject"
  get "/sb/rest/sms/notifications" => "sms_gateway#notifications"
  get "/sb/rest/sms/remove" => "sms_gateway#remove"
  
  get '/cupons/sponsor/:id' => "prize_codes#sponsor"

  get '/phones' => "users#phones"

  get '/premios/admin' => "prizes#admin"
  resources :users do
    resources :reports, :except => [:show]
    resources :posts
    collection do
      get 'special_new'
      post 'special_create'
      put 'block'
    end
  end
  
  resources :sponsors
  
  resources :dashboard
  resources :reports do
    collection do
      put 'update'
      post 'verify'
      post 'problem'
      post 'gateway'
    end
  end
  
  resources :houses do
    resources :posts
  end
  
  resources :badges
  resource :session, :only => [:new, :create, :destroy]
  match 'exit' => 'sessions#destroy', :as => :logout
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :verifications
  resources :forums, :only => [:index]
  resources :neighborhoods, :only => [:show]
  resources :buy_ins, :only => [:new, :create, :destroy]
  resources :group_buy_ins, :only => [:new, :create, :destroy]
  resources :prizes, :path => "premios"
  resources :prize_codes, :only => [:new, :create, :destroy, :show, :index], :path => "coupons"

  root :to => 'home#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
  attr_accessible :prize_id, :user_id
  belongs_to :user
  belongs_to :prize
  validates :user, :presence => true
  validates :prize, :presence => true
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @badges }
    end
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
    @badge = Badge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/new
  # GET /badges/new.json
  def new
    @badge = Badge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @badge }
    end
  end

  # GET /badges/1/edit
  def edit
    @badge = Badge.find(params[:id])
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(params[:badge])

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render json: @badge, status: :created, location: @badge }
      else
        format.html { render action: "new" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /badges/1
  # PUT /badges/1.json
  def update
    @badge = Badge.find(params[:id])

    respond_to do |format|
      if @badge.update_attributes(params[:badge])
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :prize_id %><br />
    <%= f.number_field :prize_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <tr>
    <th>User</th>
    <th>Prize</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @badges.each do |badge| %>
  <tr>
    <td><%= badge.user_id %></td>
    <td><%= badge.prize_id %></td>
    <td><%= link_to 'Show', badge %></td>
    <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
    <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @badge.user_id %>
</p>

<p>
  <b>Prize:</b>
  <%= @badge.prize_id %>
</p>


<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>