config/routes.rb
Dengue::Application.routes.draw do
  
  resources :feedbacks

  resources :notices

  match "/home/:id" => "home#index", :as => "Home"
  match "/faq" => 'home#faq'
  match "/manual" => "home#manual"
  match "/howto" => "home#howto"
  match '/contact' => 'home#contact'
  match 'about' => 'home#about'
  match '/education' => 'home#education'
  match '/credit' => 'home#credit'

  match "/user/:id/prize_codes" => 'prize_codes#index'
  match "/user/:id/prize_codes/:prize_id" => 'prize_codes#show'
  match "/user/:id/prize_codes/:prize_id/redeem/:prize_code_id" => 'prize_codes#redeem'
  post 'premios/:id' => "prizes#new_prize_code"
  match "/user/:id/buy_prize/:prize_id" => 'users#buy_prize'
  get "dashboard/index"
  get "password_resets/new"
  post "reports/sms"
  
  get "torpedos/:id" => "reports#torpedos"
  get "/sb/rest/sms/inject" => "sms_gateway#inject"
  get "/sb/rest/sms/notifications" => "sms_gateway#notifications"
  get "/sb/rest/sms/remove" => "sms_gateway#remove"
  
  get '/cupons/sponsor/:id' => "prize_codes#sponsor"

  get '/phones' => "users#phones"

  get '/premios/admin' => "prizes#admin"
  resources :users do
    resources :reports, :except => [:show]
    resources :posts
    collection do
      get 'special_new'
      post 'special_create'
      put 'block'
    end
  end
  
  resources :sponsors
  
  resources :dashboard
  resources :reports do
    collection do
      put 'update'
      post 'verify'
      post 'problem'
      post 'gateway'
    end
  end
  
  resources :houses do
    resources :posts
  end
  
  resources :badges
  resource :session, :only => [:new, :create, :destroy]
  match 'exit' => 'sessions#destroy', :as => :logout
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :verifications
  resources :forums, :only => [:index]
  resources :neighborhoods, :only => [:show]
  resources :buy_ins, :only => [:new, :create, :destroy]
  resources :group_buy_ins, :only => [:new, :create, :destroy]
  resources :prizes, :path => "premios"
  resources :prize_codes, :only => [:new, :create, :destroy, :show, :index], :path => "coupons"

  root :to => 'home#index'

end

app/models/buy_in.rb
# == Schema Information
#
# Table name: buy_ins
#
#  id              :integer          not null, primary key
#  group_buy_in_id :integer
#  user_id         :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  accepted        :boolean
#  expired         :boolean          default(FALSE), not null
#

class BuyIn < ActiveRecord::Base
  attr_accessible :group_buy_in_id, :user_id, :accepted, :expired
  belongs_to :user
  belongs_to :group_buy_in
  validates :user, :presence => true
  validates :group_buy_in, :presence => true

  def send_email_invitation
    UserMailer.group_buy_in_inviation(self.user, self.group_buy_in).deliver
  end

  #Called when user clicks on "decline" link
  def send_decline_email
    UserMailer.decline_invitation(self.group_buy_in.user, self).deliver
  end

  #Called when user clicks on "accept" link
  def send_accept_email
    if self.user.join_group_buy_in(self.group_buy_in_id)
      self.accepted = true
      if self.group_buy_in.has_enough_buyers
        self.group_buy_in.buy_item
        UserMailer.item_bought(self.group_buy_in.user, self.group_buy_in).deliver
      else
        UserMailer.accept_invitation(self.group_buy_in.user, self).deliver
      end
    end
  end

  def self.set_invites_expired
    BuyIn.all.each do |buyIn|
      buyIn.expired = true if 1.days.ago > buyIn.created_at
    end
  end

end

app/controllers/buy_ins_controller.rb
class BuyInsController < ApplicationController
  # GET /buy_ins
  # GET /buy_ins.json
  def index
    @buy_ins = BuyIn.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buy_ins }
    end
  end

  # GET /buy_ins/1
  # GET /buy_ins/1.json
  def show
    @buy_in = BuyIn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @buy_in }
    end
  end

  # GET /buy_ins/new
  # GET /buy_ins/new.json
  def new
    @buy_in = BuyIn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @buy_in }
    end
  end

  # GET /buy_ins/1/edit
  def edit
    @buy_in = BuyIn.find(params[:id])
  end

  # POST /buy_ins
  # POST /buy_ins.json
  def create
    @buy_in = BuyIn.new(params[:buy_in])

    respond_to do |format|
      if @buy_in.save
        format.html { redirect_to @buy_in, notice: 'Buy in was successfully created.' }
        format.json { render json: @buy_in, status: :created, location: @buy_in }
      else
        format.html { render action: "new" }
        format.json { render json: @buy_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buy_ins/1
  # PUT /buy_ins/1.json
  def update
    @buy_in = BuyIn.find(params[:id])

    respond_to do |format|
      if @buy_in.update_attributes(params[:buy_in])
        format.html { redirect_to @buy_in, notice: 'Buy in was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @buy_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buy_ins/1
  # DELETE /buy_ins/1.json
  def destroy
    @buy_in = BuyIn.find(params[:id])
    @buy_in.destroy

    respond_to do |format|
      format.html { redirect_to buy_ins_url }
      format.json { head :no_content }
    end
  end

  def accept
    @buyIn = BuyIn.find(params[:id])
    @buyIn.send_accept_email
    @buyIn.destroy
  end

  def decline
    @buyIn = BuyIn.find(params[:id])
    @buyIn.send_decline_email
    @buyIn.destroy
  end

end

app/helpers/buy_ins_helper.rb
module BuyInsHelper
end

app/views/buy_ins/_form.html.erb
<%= form_for(@buy_in) do |f| %>
  <% if @buy_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy_in.errors.count, "error") %> prohibited this buy_in from being saved:</h2>

      <ul>
      <% @buy_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :group_buy_in_id %><br />
    <%= f.number_field :group_buy_in_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buy_ins/edit.html.erb
<h1>Editing buy_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy_in %> |
<%= link_to 'Back', buy_ins_path %>

app/views/buy_ins/index.html.erb
<h1>Listing buy_ins</h1>

<table>
  <tr>
    <th>Group buy in</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buy_ins.each do |buy_in| %>
  <tr>
    <td><%= buy_in.group_buy_in_id %></td>
    <td><%= buy_in.user_id %></td>
    <td><%= link_to 'Show', buy_in %></td>
    <td><%= link_to 'Edit', edit_buy_in_path(buy_in) %></td>
    <td><%= link_to 'Destroy', buy_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buy in', new_buy_in_path %>

app/views/buy_ins/new.html.erb
<h1>New buy_in</h1>

<%= render 'form' %>

<%= link_to 'Back', buy_ins_path %>

app/views/buy_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Group buy in:</b>
  <%= @buy_in.group_buy_in_id %>
</p>

<p>
  <b>User:</b>
  <%= @buy_in.user_id %>
</p>


<%= link_to 'Edit', edit_buy_in_path(@buy_in) %> |
<%= link_to 'Back', buy_ins_path %>