config/routes.rb
Dengue::Application.routes.draw do
  
  resources :feedbacks

  resources :notices

  match "/home/:id" => "home#index", :as => "Home"
  match "/faq" => 'home#faq'
  match "/manual" => "home#manual"
  match "/howto" => "home#howto"
  match '/contact' => 'home#contact'
  match 'about' => 'home#about'
  match '/education' => 'home#education'
  match '/credit' => 'home#credit'

  match "/user/:id/prize_codes" => 'prize_codes#index'
  match "/user/:id/prize_codes/:prize_id" => 'prize_codes#show'
  match "/user/:id/prize_codes/:prize_id/redeem/:prize_code_id" => 'prize_codes#redeem'
  post 'premios/:id' => "prizes#new_prize_code"
  match "/user/:id/buy_prize/:prize_id" => 'users#buy_prize'
  get "dashboard/index"
  get "password_resets/new"
  post "reports/sms"
  
  get "torpedos/:id" => "reports#torpedos"
  get "/sb/rest/sms/inject" => "sms_gateway#inject"
  get "/sb/rest/sms/notifications" => "sms_gateway#notifications"
  get "/sb/rest/sms/remove" => "sms_gateway#remove"
  
  get '/cupons/sponsor/:id' => "prize_codes#sponsor"

  get '/phones' => "users#phones"

  get '/premios/admin' => "prizes#admin"
  resources :users do
    resources :reports, :except => [:show]
    resources :posts
    collection do
      get 'special_new'
      post 'special_create'
      put 'block'
    end
  end
  
  resources :sponsors
  
  resources :dashboard
  resources :reports do
    collection do
      put 'update'
      post 'verify'
      post 'problem'
      post 'gateway'
    end
  end
  
  resources :houses do
    resources :posts
  end
  
  resources :badges
  resource :session, :only => [:new, :create, :destroy]
  match 'exit' => 'sessions#destroy', :as => :logout
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :verifications
  resources :forums, :only => [:index]
  resources :neighborhoods, :only => [:show]
  resources :buy_ins, :only => [:new, :create, :destroy]
  resources :group_buy_ins, :only => [:new, :create, :destroy]
  resources :prizes, :path => "premios"
  resources :prize_codes, :only => [:new, :create, :destroy, :show, :index], :path => "coupons"

  root :to => 'home#index'

end

app/models/neighborhood.rb
# == Schema Information
#
# Table name: neighborhoods
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  coordinator_id :integer
#

class Neighborhood < ActiveRecord::Base
  attr_accessible :name

  has_many :locations
  has_many :houses, :through => :locations
  has_many :members, :through => :houses
  has_many :reports, :through => :locations

  has_many :notices
  belongs_to :coordinator, :class_name => "User"
  has_many :health_agents, :through => :houses, :source => "members", :conditions => "is_health_agent = 1"

  validates :name, :presence => true

  def rank
    0
  end
  
  def total_reports
    total_reports = []
    self.members.each do |member|
      member.reports.each do |report|
        total_report = total_reports.append(report)
      end
    end
    total_reports
  end
  
  def open_reports
    open_reports = []
    self.members.each do |member|
      member.reports.each do |report|
        open_report = open_reports.append(report) if report.status == :reported
      end
    end
    open_reports
  end
    
  def eliminated_reports
    eliminated_reports = []
    self.members.each do |member|
      member.reports.each do |report|
        eliminated_report = eliminated_reports.append(report) if report.status == :eliminated
      end
    end
    eliminated_reports
  end
  
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  
  def show
    @neighborhood = Neighborhood.find(params[:id])
    head :not_found and return if @neighborhood.nil?
    
    @participants = @neighborhood.members.where('role != ?', "lojista").where(is_blocked: false)
    @participants_view_active = ''

    @houses = @participants.map { |participant| participant.house }.uniq
    @total_reports_in_neighborhood = @neighborhood.total_reports.count
    @opened_reports_in_neighborhood = @neighborhood.open_reports.count
    @eliminated_reports_in_neighborhood = @neighborhood.eliminated_reports.count
    @number_of_houses = @houses.count
    @number_of_participants = @participants.count
    
    @notices = @neighborhood.notices
    @highlightNeighborhoodItem = ""
    
    if (@current_user != nil && (@neighborhood.members.member? @current_user)) 
      @highlightNeighborhoodItem = "nav_highlight"
    end
    
    
    @houses_view_active = ''
    
    if params[:view] == 'participants'
      @participants_view_active = 'active'
    else # view == houses
      @houses_view_active = 'active '
    end
    
    @coordinators = @participants.where(:role => "coordenador")
    @verifiers = @participants.where(:role => "verificador")
    @coordinator_blogs = @participants.where(:role => "coordenador").map { |coor| coor.posts.last }.select{ |x| !x.nil?}.sort { |x, y| y.created_at <=> x.created_at}
    @verifier_blogs = @participants.where(:role => "verificador").map { |veri| veri.posts.last }.select{ |x| !x.nil?}.sort { |x, y| y.created_at <=> x.created_at }
    # @notices = Notice.where(:)

    @sponsors = @neighborhood.members.where(:role => "lojista")
    @random_sponsors = []
    9.times do
      @random_sponsors.push('home_images/sponsor'+(rand(5)+1).to_s+'.png')
    end
  
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/new.html.haml
.row
  #top_section
    #neighborhood_of
      %h2.inline.darkgray_text Neighborhood of
      %h1.inline#neighborhood_name #{@neighborhood.name}
    #neighborhood_status_bar
      %ul
        %li
          #rank_box.inline
            %h2.inline No.
            /* doesn't actually work yet... */
            %h2.inline #{@neighborhood.rank}
            /*                               */
        %li
          #status_text
            %h1= @neighborhood.reports.count
            %h3 total reports made
        %li
          #neighborhood_open_report_button
            .button_text
              %h1.darkgray_text= @neighborhood.reports.where(:status_cd => Report.reported).count
              %p.darkgray_text open
        %li
          #neighborhood_claimed_report_button
            .button_text
              %h1.darkgray_text= @neighborhood.reports.where(:status_cd => Report.claimed).count
              %p.darkgray_text claimed
        %li
          #neighborhood_resolved_report_button
            .button_text
              %h1.darkgray_text= @neighborhood.reports.where(:status_cd => Report.eliminated).count
              %p.darkgray_text resolved
        %li
          #status_text
            %h1.darkgray_text= @neighborhood.houses.count
            %h3.darkgray_text houses
        %li
          #status_text
            %h1.darkgray_text= @neighborhood.members.count
            %h3.darkgray_text participants

#middle_section
  #left_section
    %a#houses_button{:href => '#'} Houses
    %a#participants_button{:href => '#'} Participants
    %a#health_agents_button{:href => '#'} Health Agents
    %ul#houses
      - for house in @neighborhood.houses
        %li.member
          %figure.image_placeholder.photo
          %p= house.name
    %ul#participants
      - for member in @neighborhood.members
        %li.member
          %figure.image_placeholder.photo
          %p= member.username
          %p= member.house.name
    %ul#health_agents
      - for agent in @neighborhood.health_agents
        %li.member
          %figure.image_placeholder.photo
          %p= agent.username
          %p= agent.house.name

  #right_section
    %h3 Community Coordinator
    .featured_agent_section
      .agent_photo
      #h3 Benson Ma
      .agent_description
        UC Berkeley Student. Major in Bioengineering and Computer Science.
      .view_profile  
        view profile    
    %h3 Featured Health Agent
    .featured_agent_section
      .agent_photo
      #h3 Katie Fleming
      .agent_description
        UC Berkeley Student. Major in Anthropology
      .view_profile  
        view profile
    %h3 Local Sponsors
    #local_sponsors_section
      %ul
        %li= image_tag("home_images/sponsor1.png")
        %li= image_tag("home_images/sponsor2.png")
        %li= image_tag("home_images/sponsor3.png")
        %li= image_tag("home_images/sponsor4.png")
        %li= image_tag("home_images/sponsor5.png")
        %li= image_tag("home_images/sponsor1.png")
        %li= image_tag("home_images/sponsor2.png")
        %li= image_tag("home_images/sponsor3.png")
        %li= image_tag("home_images/sponsor4.png")

#bottom_section
  %h2 Community News
  .news_block
    .title How to Design Your Own Logo
    .type course
    .content
      %figure.image_placeholder.photo
      .message Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    .clearfloat
  .news_block
    .title Photography Exhibit
    .type event
    .content
      %figure.image_placeholder.photo
      .message Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    .clearfloat
  .news_block
    .title Dengue and Public Health
    .type lecture
    .content
      %figure.image_placeholder.photo
      .message Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

app/views/neighborhoods/show.html.haml
.row
  .span8.offset1
    %h1 Comunidade da #{@neighborhood.name}
.row
  #neighborhood_stats.offset1
    .span3
      %b= @total_reports_in_neighborhood
      %br Total de focos marcados
    .span3
      .row
        #neighborhood_open_report_button.span1 
        .span2
          %b= @opened_reports_in_neighborhood
          %br em aberto
    .span3{:style => "margin-left:-35px;"}
      .row
        #neighborhood_resolved_report_button.span1 
        .span2
          %b= @eliminated_reports_in_neighborhood
          %br eliminados
%br
%br


.row
  #neighborhood_view{:style => "font-weight:bold;"}
    .span.offset1
      = link_to 'Casas (' + @number_of_houses.to_s + ')', neighborhood_path(params[:id]), :class => @houses_view_active
    .span
      = link_to 'Participantes (' + @number_of_participants.to_s + ')', neighborhood_path(params[:id], :view => 'participants'), :class => @participants_view_active
%br
.row
  - if params[:view] == 'participants'
    .span11.offset1
      %ul#neighborhood_participants_list
        - @participants.each do |participant|
          %li.neighborhood_participant_photo_thumb.span3
            - if participant.profile_photo_file_name.nil?
              = link_to image_tag("default_images/profile_default_image.png"), user_path(participant)
            - else
              = link_to image_tag(participant.profile_photo.url(:large)), user_path(participant)
            
            = link_to participant.display_name, user_path(participant)
        - if @participants.count < 9
          - (12 - @participants.count).times do          
            %li.neighborhood_participant_photo_thumb.span3
              = image_tag("default_images/profile_default_image.png")
              Futuro participante
      .row{style: "margin-top:50px;"}
        %h2 Notícias da comunidade
      #neighborhood_news{style: "height:310px;overflow-x:scroll;width:690px;"}  
        %ul
          - @notices.each do |notice|
            %a{:href => notice_path(notice)}
              %li.span4.neighborhood_news_title{:style => "height:270px;position:relative;"}
                .row
                  .span5
                    - if notice.title.size > 33
                      = notice.title[0..30] + "..."
                    - else
                      = notice.title
                %br
                .row
                  .span1.neighborhood_news_thumb
                    = image_tag(notice.photo.url(:medium))
                  .span3.neighborhood_news_content
                    = notice.summary
                .row{style: 'margin-top: 20px;margin-left:10px;position:absolute;bottom:10px;width:280px;'}
                  .row
                    = notice.institution_name
                  .row
                    = notice.location
                  .row
                    Data
                    = notice.date.strftime("%d/%m/%Y")
                  .row
                    Hora
                    = notice.date.strftime("%H:%M")

      
  - else 
    .span11.offset1
      %ul#neighborhood_house_list
        - @houses.each do |house|
          %li.neighborhood_house_photo_thumb.span3
            - if house.profile_photo_file_name.nil?
              = link_to image_tag("default_images/house_default_image.png"), house_path(house)
            - else 
              = link_to image_tag(house.profile_photo.url(:large)), house_path(house)
            = link_to house.name, house_path(house)
        - if @houses.count < 7
          - (9 - @houses.count).times do          
            %li.neighborhood_house_photo_thumb.span3
              = image_tag("default_images/house_default_image.png")
              Futura casa           
      .row{style: "margin-top:50px;"}
        %h2 Notícias da comunidade
      #neighborhood_news{style: "height:310px;overflow-x:scroll;width:690px;"}  
        %ul
          - @notices.each do |notice|
            %a{:href => notice_path(notice)}
              %li.span4.neighborhood_news_title{:style => "height:270px;position:relative;"}
                .row
                  .span5
                    - if notice.title.size > 33
                      = notice.title[0..30] + "..."
                    - else
                      = notice.title
                %br
                .row
                  .span1.neighborhood_news_thumb
                    = image_tag(notice.photo.url(:medium))
                  .span3.neighborhood_news_content
                    = notice.summary
                .row{style: 'margin-top: 20px;margin-left:10px;position:absolute;bottom:10px;'}
                  .row
                    = notice.institution_name
                  .row
                    = notice.location
                  .row
                    Data
                    = notice.date.strftime("%d/%m/%Y")
                  .row
                    Hora
                    = notice.date.strftime("%H:%M")
  #neighborhood_right_panel.span5{:style => "margin-top:-165px;margin-left:0px;"}
    %h2 Destaques da comunidade
    .row
      %h3{:style => "margin-left:10px;"} Coordenadores comunitários
      #neighborhood_coordinator.span5
        - @coordinator_blogs.each do |blog|
          - if blog
            .neighborhood_profile_box{style: "margin-bottom:10px;"}
              .span1.neighborhood_pf_picture
                = image_tag(blog.user.profile_photo.url(:small))                     
              .neighborhood_quote{:style => "margin-top:-8px;padding-left:10px;"}
                .neighborhood_person_name
                  = link_to blog.user.display_name, user_path(blog.user)
                .neighborhood_post
                  = auto_link(blog.content)            
              
    .row
      %h3{:style => "margin-left:10px;"} Verificadores
      #neighborhood_health_agent.span5
        - @verifier_blogs.each do |blog|
          - if blog
            .neighborhood_profile_box
              .span1.neighborhood_pf_picture
                = image_tag(blog.user.profile_photo.url(:small))
              .neighborhood_quote{:style => "margin-top:-8px;padding-left:10px;"}
                .neighborhood_person_name
                  = link_to blog.user.display_name, user_path(blog.user)    
                .neighboorhood_past
                  = auto_link(blog.content)
  .row
    .offset1.span12{:style => "width:650px;"}
      #neighborhood_sponsors{:style => "margin-top:20px;"}
        %h2 Patrocinadores
        %ul{:style => "height:120px; overflow-x:auto;"}
          - @sponsors.each do |sponsor|
            %li{:style => "width:100px; height:100px;display:inline;"}
              - if sponsor.house.profile_photo_file_name.nil?
                .logo_box{style: "width: 98px; height: 78px;padding-top:20px;margin-right: 5px;"}
                  = link_to sponsor.house.name, sponsor_path(sponsor)
              - else
                = link_to image_tag(sponsor.house.profile_photo.url(:medium), :width => 100, :height => 100), sponsor_path(sponsor)