config/routes.rb
Dengue::Application.routes.draw do
  
  resources :feedbacks

  resources :notices

  match "/home/:id" => "home#index", :as => "Home"
  match "/faq" => 'home#faq'
  match "/manual" => "home#manual"
  match "/howto" => "home#howto"
  match '/contact' => 'home#contact'
  match 'about' => 'home#about'
  match '/education' => 'home#education'
  match '/credit' => 'home#credit'

  match "/user/:id/prize_codes" => 'prize_codes#index'
  match "/user/:id/prize_codes/:prize_id" => 'prize_codes#show'
  match "/user/:id/prize_codes/:prize_id/redeem/:prize_code_id" => 'prize_codes#redeem'
  post 'premios/:id' => "prizes#new_prize_code"
  match "/user/:id/buy_prize/:prize_id" => 'users#buy_prize'
  get "dashboard/index"
  get "password_resets/new"
  post "reports/sms"
  
  get "torpedos/:id" => "reports#torpedos"
  get "/sb/rest/sms/inject" => "sms_gateway#inject"
  get "/sb/rest/sms/notifications" => "sms_gateway#notifications"
  get "/sb/rest/sms/remove" => "sms_gateway#remove"
  
  get '/cupons/sponsor/:id' => "prize_codes#sponsor"

  get '/phones' => "users#phones"

  get '/premios/admin' => "prizes#admin"
  resources :users do
    resources :reports, :except => [:show]
    resources :posts
    collection do
      get 'special_new'
      post 'special_create'
      put 'block'
    end
  end
  
  resources :sponsors
  
  resources :dashboard
  resources :reports do
    collection do
      put 'update'
      post 'verify'
      post 'problem'
      post 'gateway'
    end
  end
  
  resources :houses do
    resources :posts
  end
  
  resources :badges
  resource :session, :only => [:new, :create, :destroy]
  match 'exit' => 'sessions#destroy', :as => :logout
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :verifications
  resources :forums, :only => [:index]
  resources :neighborhoods, :only => [:show]
  resources :buy_ins, :only => [:new, :create, :destroy]
  resources :group_buy_ins, :only => [:new, :create, :destroy]
  resources :prizes, :path => "premios"
  resources :prize_codes, :only => [:new, :create, :destroy, :show, :index], :path => "coupons"

  root :to => 'home#index'

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                        :integer          not null, primary key
#  report                    :text
#  reporter_id               :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  status_cd                 :integer
#  eliminator_id             :integer
#  location_id               :integer
#  before_photo_file_name    :string(255)
#  before_photo_content_type :string(255)
#  before_photo_file_size    :integer
#  before_photo_updated_at   :datetime
#  after_photo_file_name     :string(255)
#  after_photo_content_type  :string(255)
#  after_photo_file_size     :integer
#  after_photo_updated_at    :datetime
#  elimination_type          :string
#  elimination_method        :string


class Report < ActiveRecord::Base
  attr_accessible :report, :elimination_type, :elimination_method, :verifier_id, :reporter_name, :eliminator_name, :location_id, :reporter, :location, :sms

  has_attached_file :before_photo, :styles => {:medium => "150x150>", :thumb => "100x100>"}, :default_url => 'default_images/report_before_photo.png'
  has_attached_file :after_photo, :styles => {:medium => "150x150>", :thumb => "100x100>"}, :default_url => 'default_images/report_after_photo.png'
    
  belongs_to :reporter, :class_name => "User"
  belongs_to :eliminator, :class_name => "User"
  belongs_to :location
  has_many :feeds, :as => :target
  
  belongs_to :verifier, :class_name => "User"
  belongs_to :resolved_verifier, :class_name => "User"
  validates :reporter_id, :presence => true
  validates :location_id, :presence => true
  validates :status, :presence => true

  # validates_attachment :before_photo, presence: true

  as_enum :status, [:reported, :eliminated]

  scope :sms, where(sms: true)

  before_save :set_names

  def self.create_from_user(report_content, params)
    create(:report => report_content) do |r|
      r.reporter_id = params[:reporter] && params[:reporter].id
      r.location_id = params[:location] && params[:location].id
      r.status = params[:status]

      # optional parameters
      r.eliminator_id = params[:eliminator] && params[:eliminator].id
      
      if params[:before_photo]
        r.before_photo = params[:before_photo]
      end
      
      if params[:after_photo]
        r.after_photo = params[:after_photo]
      end
    end
  end

  # callback to create the feeds
  after_save do |report|
    Feed.create_from_object(report, report.reporter_id, :reported) if report.reporter_id_changed?
    Feed.create_from_object(report, report.eliminator_id, :eliminated) if report.eliminator_id_changed?
  end
  
  def neighborhood
    location.neighborhood
  end
  
  def strftime_with(type)
    if type == :created_at
      self.created_at.strftime("%d/%m/%Y")
    elsif type == :updated_at
      self.updated_at.strftime("%d/%m/%Y")
    elsif type == :eliminated_at
      self.eliminated_at != nil ? self.eliminated_at.strftime("%d/%m/%Y") : ""
    else 
      ""
    end
  end  
    
  def self.unverified_reports
    Report.where(:status_cd => Report.reported)
  end
  
  def complete_address
    self.location.complete_address
  end
  
  def self.within_bounds(bounds)
    reports_in_bounds = []
    for report in Report.all(:order => "created_at desc")
      if self.inBounds(report.location, bounds)
        reports_in_bounds.append(report)
        puts report.inspect + ' added'
      end 
    end
    return reports_in_bounds
  end
  
  def self.inBounds(location, bounds)
    swlng = bounds[1]
    swlat = bounds[0]
    nelng = bounds[3]
    nelat = bounds[2]
    sw = Geokit::LatLng.new(swlat, swlng)
    ne = Geokit::LatLng.new(nelat, nelng)
    calculated_bounds = Geokit::Bounds.new(sw,ne)
    point = Geokit::LatLng.new(location.latitude, location.longitude)
    return calculated_bounds.contains?(point)
  end

  def expired?
    self.created_at and self.created_at + 3600 * 24 * 2 < Time.new
  end

  def expire_date
    self.created_at + 3600 * 24 * 2
  end

  def not_sms?
    not sms
  end

  def set_names
    if self.reporter_id
      self.reporter_name = self.reporter.display_name
    end

    if self.eliminator_id
      self.eliminator_name = self.eliminator.display_name
    end
  end

  def self.invalidateExpired
    Report.where("created_at < ?", (Time.now - 3.days)).where(:status_cd => 0).each do |report|
      report.status_cd =1
      report.report = "This report has expired, it was not resolved within three days"
      report.save!
    end
  end
end

app/controllers/reports_controller.rb
#!/bin/env ruby
# encoding: utf-8

class ReportsController < ApplicationController

  before_filter :require_login, :except => [:sms, :verification]

  def index 
    @current_report = params[:report]    
    @current_user != nil ? @highlightReportItem = "nav_highlight" : @highlightReportItem = ""
    params[:view] = 'recent' if params[:view].nil? || params[:view] == "undefined"
    params[:view] == 'recent' ? @reports_feed_button_active = "active" : @reports_feed_button_active = ""
    params[:view] == 'open' ? @reports_open_button_active = "active" : @reports_open_button_active = ""
    params[:view] == 'eliminate' ? @reports_resolved_button_active = "active" : @reports_resolved_button_active = ""
    params[:view] == 'make_report' ?  @make_report_button_active = "active" : @make_report_button_active = ""
    
    if params[:view] == "make_report"
      @report = Report.new
    end
    
    @elimination_method_select = EliminationMethods.field_select
    @elimination_types = EliminationMethods.types
    reports_with_status_filtered = []
    locations = []
    open_locations = []
    eliminated_locations = []
    @prantinho = EliminationMethods.prantinho
    @pneu = EliminationMethods.pneu
    @lixo = EliminationMethods.lixo
    @pequenos = EliminationMethods.pequenos
    @caixa = EliminationMethods.caixa
    @grandes = EliminationMethods.grandes
    @calha = EliminationMethods.calha
    @registros = EliminationMethods.registros
    @laje = EliminationMethods.laje
    @piscinas = EliminationMethods.piscinas
    @pocas = EliminationMethods.pocas
    @ralos = EliminationMethods.ralos
    @plantas = EliminationMethods.plantas
    @points = EliminationMethods.points
    Report.order("created_at DESC").each do |report|
      if report.location.latitude and (report.reporter == @current_user or report.elimination_type)
        if params[:view] == 'recent' || params[:view] == 'make_report'
          reports_with_status_filtered << report
          if report.status_cd == 1
            eliminated_locations << report.location
          else
            open_locations << report.location
          end
          locations << report.location
        elsif params[:view] == 'open' && report.status == :reported
          reports_with_status_filtered << report
          open_locations << report.location
        elsif params[:view] == 'eliminate' && report.status == :eliminated
          reports_with_status_filtered << report
          eliminated_locations << report.location
        end
      end
    end
    
    # @map_json = locations.map { |location| {"lat" => location.latitude, "lng" => location.longitude} }.to_json

    @markers = locations.map { |location| location.info}
    @open_markers = open_locations.map { |location| location.info}
    @eliminated_markers = eliminated_locations.map { |location| location.info}
    @reports = reports_with_status_filtered
    @counts = Report.group(:location_id).count
    @open_counts = Report.where(status_cd: 0).group(:location_id).count
    @eliminated_counts = Report.where(status_cd: 1).group(:location_id).count
    @open_feed = @reports
    @eliminate_feed = @reports
  end
  
  def new
    @report = Report.new
  end

  def create    

    if request.post?
      address = params[:street_type] + " " + params[:street_name] + " " + params[:street_number]
      flash[:street_type] = params[:street_type]
      flash[:street_name] = params[:street_name]
      flash[:street_number] = params[:street_number]
      flash[:description] = params[:report][:report]
      flash[:x] = params[:x]
      flash[:y] = params[:y]
      location = Location.find_by_address(address)
      
      if params[:x].empty? or params[:y].empty?
        flash[:alert] = "Você precisa marcar uma localização válida para o seu foco."
        redirect_to :back
        return
      end

      if location.nil?
        location = Location.new(:street_type => params[:street_type], :street_name => params[:street_name], :street_number => params[:street_number], latitude: params[:x], longitude: params[:y])
        location.save
      else
        location.latitude = params[:x]
        location.latitude = params[:y]
      end
      
      if params[:report][:report] == ""
        flash[:alert] = "Você tem que descrever o local e/ou o foco."
        flash[:address] = address
        @report = Report.new(:location => location)
        redirect_to :back
        return
      end

      if !params[:report][:before_photo] and params[:report]
        flash[:alert] = "Você tem que carregar uma foto do foco encontrado."  
        @report = Report.new(:location => location)
        @report.report = params[:report][:report]
        redirect_to :back
        return
      end



      @report = Report.create_from_user("", :status => :reported, :reporter => @current_user, :location => location)
      @report.report = params[:report][:report]
      

      @report.before_photo = params[:report][:before_photo]
    
      if @report.save
        if @current_user != nil and params[:before_photo]
          # @current_user.update_attribute(:points, @current_user.points + 100)
        end
        
        flash[:notice] = 'Foco marcado com sucesso!'
        redirect_to :action=>'index', view: 'recent'
      else
        flash[:alert] = "here"
        redirect_to :back
      end
    end
  end
  
  def edit
    @report = @current_user.created_reports.find(params[:id])
  end
    
  def verification
    @unverified_reports = Report.unverified_reports
  end
  
  def sms
    logger = Logger.new(STDOUT)  
    logger.info params[:Body].inspect
    logger.info params[:From].inspect
    
    @account_sid = 'AC696e86d23ebba91cbf65f1383cf63e7d'
    @auth_token = 'a49ee186176ead11c760fd77aeaeb26c'
    @client = Twilio::REST::Client.new(@account_sid, @auth_token)
    @account = @client.account
    
    login = params[:From].delete('+')
    user = User.find_by_username(login)    
  
    if !user
      password = ApplicationHelper.temp_password_generator
      logger.info password
      user = User.new(:username => login, :password => password, :password_confirmation => password)
      logger.info user.inspect
      
      if user.save
        logger.info "new user created and send welcome report"
        response = 'username: ' + params[:From].delete('+') + ' Temporary password: ' + password + ' To login to the site, go to http://www.denguetorpedo.com' 
        @account.sms.messages.create(:from => '+15109854798', :to => params[:From], :body  => response)
      end
    end
    
    logger.info "parsing the sms text..."
    parser = MailParser::Parser.new(params[:Body], 'sms')
    
    if parser.report && parser.nation && parser.city && parser.address && parser.state
      
      if parser.neighborhood.nil?
        neighborhood = ""
      else
        neighborhood = parser.neighborhood
      end
      
      logger.debug "Parsed data = nation: " + parser.nation + " address: " + parser.address + " neighborhood: " + neighborhood + " city: " + parser.city + " state: " + parser.state + " report: " + parser.report
      report = Report.new(:user_id => user.id, :nation => parser.nation, :address => parser.address, :neighborhood => neighborhood, :city => parser.city, :state => parser.state, :report => parser.report)
      
      if report.save 
        logger.info("New report sucessfully added")
        @account.sms.messages.create(:from => '+15109854798', :to => params[:From], :body  => 'Congratulation! your report has been processed and added to our database')
      else
        logger.info("New report failed to add")
        @account.sms.messages.create(:from => '+15109854798', :to => params[:From], :body  => 'I am sorry, but something went wrong in our system. We were unable to add your report')
      end
    else
      logger.info "No match was found or some fields were not specified"
      @account.sms.messages.create(:from => '+15109854798', :to => params[:From], :body  => 'We could not understand your report because some hashtags were missing...')
    end
  end

  def update
    if request.put?
      @report = Report.find(params[:report_id])

      if params[:elimination_type] == ""
        flash[:error] = "Você tem que escolher um tipo de foco."
        redirect_to :back
        return
      end

      if @report.elimination_type.nil? and params[:elimination_type]
        @report.elimination_type = params[:elimination_type]
        @report.save
        flash[:notice] = "Tipo de foco atualizado com sucesso."
        @current_user.update_attribute(:points, @current_user.points + 50)
        @current_user.update_attribute(:total_points, @current_user.total_points + 50)
        redirect_to :back
        return
      end
 
      if params[:report_description]
        @report.report = params[:report_description]
        @report.save
      end
      
      if !params[:eliminate] and @report.after_photo_file_size.nil?
        flash[:error] = 'Você tem que carregar uma foto do foco eliminado.'
        redirect_to(:back)
        return
      end

      if params[:selected_elimination_method] == ""
        # @report.elimination_type = params[:elimination_type]
        # @report.save

        if @report.after_photo_file_size.nil?
          if params[:eliminate] and params[:eliminate][:after_photo] != nil
          # user uploaded an after photo
            @report.after_photo = params[:eliminate][:after_photo]
            @current_user.points += 400
            @current_user.total_points += 400
            @current_user.save
            @report.save
          end
        end

        flash[:error] = "Você tem que escolher um método de eliminação."
        redirect_to :back
        return
      end
      
      if @report.after_photo_file_size.nil?
        if params[:eliminate] and params[:eliminate][:after_photo] != nil 
          # user uploaded an after photo
          @report.after_photo = params[:eliminate][:after_photo]
          @current_user.points += 400

app/helpers/reports_helper.rb
module ReportsHelper
  def random_sponsors
    random_sponsors = []
    9.times do
      random_sponsors.push('home_images/sponsor'+(rand(5)+1).to_s+'.png')
    end 
    random_sponsors   
  end
  
end

app/views/reports/_eliminate_list.html.haml
#user_reports
  - for report in @eliminate_feed
    = render :partial => 'reports/resolved', :object => report

app/views/reports/_open.html.haml
.rp_report.rp_open_report
  .row
    .rp_report_status.status
      - if open.expired?
        %del Em aberto
      - else
        Em aberto
      .rp_report_options{:style => "margin-top:-3px;"}
        - if open.isVerified == "t"
          = image_tag 'icons/reports icon/check.png', :width => 25, :height => 25, :style => "float:right;"
        - elsif open.isVerified == "f"
          = image_tag 'icons/reports icon/x.png', :width => 25, :height => 25, :style => "float:right;"
        - else
          - if !open.expired? and open.elimination_type
            - if @current_user.role == "verificador" or @current_user.role == "admin"
              = link_to (image_tag 'icons/reports icon/x.png', :width => 25, :height => 25), problem_reports_path(:id => open.id), method: :post, :style => "float:right;"
              = link_to (image_tag 'icons/reports icon/check.png', :width => 25, :height => 25), verify_reports_path(:id => open.id), method: :post, :style => "float:right;"
        
        - if open.created_at + 3600 * 24 * 2 > Time.new
          - if open.elimination_type
            .countdown.countdownHolder{:style => "width:150px;height: 20px;background-color:transparent; border: none;float:right;margin-top:1px;margin-right:0px;font-size:20px;"}
            .span{style: "margin-top:3px; margin-right:10px;"}
              Tempo restante
              :javascript
                var newYear = new Date(#{open.expire_date.strftime("%s").to_i * 1000});
                $(".countdown").countdown({until: newYear, format: 'HMS', compact: 'true'});
        - else
          .span{style: "margin-top:3px; margin-right:10px;"}
            Tempo expirado
        
  .row
    .span7{:style => "margin-top:10px;"}
      %h4= open.complete_address
  .row
    .span2.rp_before_photo 
      =image_tag open.before_photo(:medium)
    .span5{style: "margin-top:9px;"}
      - if open.elimination_type
        %p{style: "margin-bottom:12px;"}= open.report

      - else     
        = text_area_tag("report_description", open.report, style: "width:430px;")
      / .row.rp_report_people
      /   Marcado por:
      /   =link_to open.reporter.display_name + " - " + open.strftime_with(:created_at), user_path(open.reporter), :class => "user"
      - if @current_user != nil
        .row
          .span7
            - if open.before_photo.url.include?("default_images/report_before_photo.png" )
              %h3{:style => "font-size: 14px;"} Carregue uma foto do foco identificado
              .eliminate_prompt
                = form_for(:eliminate, :url => {:controller => "reports", :action => "update", :html => {:autocomplete => "off", :multipart => true}}, :method=>:put) do |f|
                  = hidden_field_tag 'report_id', open.id
                  = f.file_field :before_photo
                  = submit_tag "Carregue!", :disabled => open.created_at + 3600 * 24 * 2 < Time.new
                  
            - else

              .eliminate_prompt{:style => "margin-top:5px;"}
                = form_for(:eliminate, :url => {:controller => "reports", :action => "update", :html => {:autocomplete => "off", :multipart => false}}, :method=>:put) do |f|
                  = hidden_field_tag 'report_id', open.id
                  
                  = select_tag "elimination_type", options_for_select(@elimination_types, open.elimination_type), :prompt => "Tipo de foco", :style => "width:430px;", class: "elimination_type", :disabled => (open.elimination_type != nil or @current_user.role == "visitante")
                  = select_tag "prantinho", options_for_select(@prantinho.collect{ |p| [p[1], p[0]]}), :class => "elimination_methods", :prompt => "Método de eliminação", :style => "width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante"), data: { style: "btn-success", width: "430px"}
                  = select_tag "pneu", options_for_select(@pneu.collect{ |p| [p[1], p[0]]}), :style => "display:none;width:430px;", :class => "elimination_methods", :prompt => "Método de eliminação", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "lixo", options_for_select(@lixo.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "pequenos", options_for_select(@pequenos.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "caixa", options_for_select(@caixa.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "grandes", options_for_select(@grandes.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "calha", options_for_select(@calha.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "registros", options_for_select(@registros.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "laje", options_for_select(@laje.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "piscinas", options_for_select(@piscinas.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "pocas", options_for_select(@pocas.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "ralos", options_for_select(@ralos.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = select_tag "plantas", options_for_select(@plantas.collect{ |p| [p[1], p[0]]}), :style => "display:none;", :class => "elimination_methods", :prompt => "Método de eliminação", :style => "display:none;width:430px;", disabled: (open.elimination_type.nil? or open.expired? or @current_user.role == "visitante")
                  = hidden_field_tag "selected_elimination_method"
                  / # = select_tag "method_of_elimination", options_from_collection_for_select(@elimination_type), :style => "width: 355px;" 
                  :javascript
                    $(".selectpicker").selectpicker();

                  - if open.after_photo_file_size
                    .rp_report_people
                      Foto carregada:
                      = link_to "#{open.after_photo_file_name}", open.after_photo.url, :class => "user"

                  - if open.elimination_type
                    %h3{:style => "font-size: 14px;"} Carregue uma foto do foco eliminado
                    = f.file_field :after_photo, :disabled => (open.after_photo_file_size or open.expired?)
                  %br
                  = submit_tag "Enviar!", :style => "margin-left:5px;margin-top:5px;", :disabled => ((@current_user.role == "verificador" or @current_user.role == "visitante") or open.created_at + 3600 * 24 * 2 < Time.new or open.isVerified == "f")



                  .row.rp_report_people{style: "width:430px;"}
                    - if open.elimination_type and open.reporter_id
                      Marcado por:
                      =link_to open.reporter.display_name + " " + open.strftime_with(:created_at), user_path(open.reporter), :class => "user"
                      %br

                    - if open.isVerified == "t" and open.verifier_id
                      Verificado por:
                      = link_to open.verifier.display_name + " " + open.strftime_with(:created_at), user_path(open.verifier), :class => "user"
                      %br
                    - elsif open.isVerified == "f" and open.verifier_id
                      %p{:style => "color:red;font-weight:bold;margin-top:10px;"}
                        Problema no foco marcado. Entre em contato conosco.
    .row
      .rp_report_options
        - if @current_user.admin?
          =link_to (image_tag 'icons/reports icon/delete2.png', :id=>'user_report_delete'), open, :confirm => "Você tem certeza?", :method => :delete, :style => "margin-right:5px;"

app/views/reports/_open_list.html.haml
#user_reports
  - for report in @open_feed
    - if report.reporter == @current_user or report.elimination_type
      = render :partial => '/reports/open', :object => report

app/views/reports/_resolved.html.haml
.rp_report.rp_resolved_report
  .row
    .rp_report_status.status
      Eliminado
      .rp_report_options{:style => "margin-top:-3px;"}
        - if resolved.is_resolved_verified == "t"
          = image_tag 'icons/reports icon/check.png', :width => 25, :height => 25, :style => "float:right;"
        - elsif resolved.is_resolved_verified == "f"
          = image_tag 'icons/reports icon/x.png', :width => 25, :height => 25, :style => "float:right;"
        - else
          - if @current_user.role == "verificador" or @current_user.role == "admin"
            = link_to (image_tag 'icons/reports icon/x.png', :width => 25, :height => 25), problem_reports_path(:id => resolved.id), method: :post, :style => "float:right;"
            = link_to (image_tag 'icons/reports icon/check.png', :width => 25, :height => 25), verify_reports_path(:id => resolved.id), method: :post, :style => "float:right;"     
  .row
    .span8{:style => "margin-top:10px;"}
      %h4== #{resolved.complete_address}
      
  .row
    .span2.rp_before_photo
      =image_tag resolved.before_photo(:medium), :style => "margin-bottom:10px;"

      =image_tag resolved.after_photo(:medium)
      
    .span6
      .row.rp_report_people.span6
        %h3{style: "font-weight:bold;"}Descrição da localização:
        = resolved.report
        %h3{:style => "font-weight:bold;"} Tipo de foco:
        = resolved.elimination_type
        %h3{:style => "font-weight:bold;"} Método de eliminação:
        = resolved.elimination_method
        %br
        %br
        - if resolved.reporter_id
          Marcado por:
          =link_to resolved.reporter.display_name + " " + resolved.strftime_with(:created_at), user_path(resolved.reporter), :class => "user", :style => "width:100%;"
        - else
          Marcado por: #{resolved.reporter_name + " " + resolved.strftime_with(:created_at)} 
        %br
        - if resolved.eliminator_id
          Eliminado por:
          =link_to resolved.eliminator.display_name + " " + resolved.strftime_with(:eliminated_at), user_path(resolved.eliminator), :class => "user", :style => "width:100%;"
        - else
          -if resolved.eliminated_at
            Eliminador por: #{resolved.eliminator_name + " " + resolved.strftime_with(:eliminated_at)}
        %br
        - if resolved.is_resolved_verified == "t" and resolved.resolved_verifier_id
          Verificado por:
          = link_to resolved.resolved_verifier.display_name + " " + resolved.strftime_with(:resolved_verified_at), user_path(resolved.resolved_verifier), :class => "user"
        - elsif resolved.is_resolved_verified == "f" and resolved.resolved_verifier_id
          %p{:style => "color:red;font-weight:bold;margin-top:10px;width:410px;"}
            Problema no foco marcado. Entre em contato conosco.
        
  .row
    .rp_report_options
      - if @current_user.admin?
        =link_to (image_tag 'icons/reports icon/delete2.png', :id=>'user_report_delete'), resolved, :confirm => "Você tem certeza?", :method => :delete, :style => "margin-right:5px;"